sudo: required
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install
  - sudo apt-get install -y build-essential libssl-dev python-pip python2.7-dev
  - sudo pip install -U setuptools wheel docker-cloud synapseclient[pandas,pysftp]
  - docker login --username="$DOCKER_USER" --password="$DOCKER_PASSWORD"

stages:
  - name: deploy-containers
  - name: test

jobs:
  include:
    - stage: deploy-containers
      script:
        - ./get-data-aws.sh || travis_terminate 1
        - ./container-build.sh || travis_terminate 1
        - ./container-deploy.sh || travis_terminate 1
    - stage: test
      script: npm run ci:travis
      node_js: 6
    - stage: test
      script: npm run ci:travis
      node_js: 7
    - stage: test
      script: npm run ci:travis
      node_js: 8
